"""init_auto

Revision ID: 06f2161f7b9e
Revises: 3b39deca478c
Create Date: 2021-03-24 13:31:46.794961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06f2161f7b9e'
down_revision = '3b39deca478c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('maps', sa.Column('fieldID', sa.Integer(), nullable=False))
    op.drop_constraint('maps_userID_fkey', 'maps', type_='foreignkey')
    op.create_foreign_key(None, 'maps', 'fieldProfile', ['fieldID'], ['id'])
    op.drop_column('maps', 'userID')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('maps', sa.Column('userID', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'maps', type_='foreignkey')
    op.create_foreign_key('maps_userID_fkey', 'maps', 'users', ['userID'], ['id'])
    op.drop_column('maps', 'fieldID')
    # ### end Alembic commands ###
