"""empty message

Revision ID: 114b991df428
Revises: 
Create Date: 2021-03-26 20:33:00.055181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '114b991df428'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
