"""init_auto

Revision ID: 18ca326f0a74
Revises: 2a21f568482b
Create Date: 2021-03-24 19:28:11.559357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18ca326f0a74'
down_revision = '2a21f568482b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
