"""empty message

Revision ID: 23d312d47562
Revises: 368daf56361e
Create Date: 2021-03-31 14:24:17.361907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23d312d47562'
down_revision = '368daf56361e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('marker', sa.String(), nullable=True))
    op.add_column('locations', sa.Column('path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('locations', 'path')
    op.drop_column('locations', 'marker')
    # ### end Alembic commands ###
