"""init_auto

Revision ID: 287fa95b2437
Revises: 
Create Date: 2021-03-23 21:39:44.601326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '287fa95b2437'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'action', ['action'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'action', type_='unique')
    # ### end Alembic commands ###
