"""init_auto

Revision ID: 2a21f568482b
Revises: c1280c9634fe
Create Date: 2021-03-24 19:14:47.832586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a21f568482b'
down_revision = 'c1280c9634fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
