"""empty message

Revision ID: 2cfcaf4f146d
Revises: ef3e2c33d2e4
Create Date: 2021-04-02 16:49:28.162352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cfcaf4f146d'
down_revision = 'ef3e2c33d2e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
