"""empty message

Revision ID: 368daf56361e
Revises: 734abcb12a65
Create Date: 2021-03-30 18:00:28.907489

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '368daf56361e'
down_revision = '734abcb12a65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teamPlayer', 'lastMedic')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teamPlayer', sa.Column('lastMedic', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
