"""init_auto

Revision ID: 3b39deca478c
Revises: 287fa95b2437
Create Date: 2021-03-23 21:51:46.369859

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3b39deca478c'
down_revision = '287fa95b2437'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('locations', 'lastChange')
    op.drop_column('locations', 'deactivated')
    op.drop_column('maps', 'deactivated')
    op.drop_column('maps', 'lastChange')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('maps', sa.Column('lastChange', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('maps', sa.Column('deactivated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('locations', sa.Column('deactivated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('locations', sa.Column('lastChange', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
