"""empty message

Revision ID: 8e6bd9cfe07b
Revises: 44f72051e928
Create Date: 2021-03-27 22:55:57.180326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e6bd9cfe07b'
down_revision = '44f72051e928'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gameAction', sa.Column('points', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gameAction', 'points')
    # ### end Alembic commands ###
