"""init_auto

Revision ID: 92980ac156ee
Revises: 06f2161f7b9e
Create Date: 2021-03-24 19:02:14.706793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92980ac156ee'
down_revision = '06f2161f7b9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rfid', 'userID',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rfid', 'userID',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
