"""empty message

Revision ID: a373d5d2c714
Revises: 114b991df428
Create Date: 2021-03-27 08:35:14.803393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a373d5d2c714'
down_revision = '114b991df428'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('teamPlayer', 'teamID',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('teamPlayer', 'teamID',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
