"""empty message

Revision ID: ab0f0726bed2
Revises: a373d5d2c714
Create Date: 2021-03-27 14:55:15.424634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab0f0726bed2'
down_revision = 'a373d5d2c714'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teamPlayer', sa.Column('lastMedic', sa.DateTime(), nullable=True))
    op.add_column('teamPlayer', sa.Column('rfidID', sa.Integer(), nullable=False))
    op.drop_constraint('teamPlayer_userID_fkey', 'teamPlayer', type_='foreignkey')
    op.create_foreign_key(None, 'teamPlayer', 'rfid', ['rfidID'], ['id'])
    op.drop_column('teamPlayer', 'userID')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teamPlayer', sa.Column('userID', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'teamPlayer', type_='foreignkey')
    op.create_foreign_key('teamPlayer_userID_fkey', 'teamPlayer', 'users', ['userID'], ['id'])
    op.drop_column('teamPlayer', 'rfidID')
    op.drop_column('teamPlayer', 'lastMedic')
    # ### end Alembic commands ###
