"""init_auto

Revision ID: c1280c9634fe
Revises: 92980ac156ee
Create Date: 2021-03-24 19:03:38.891939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1280c9634fe'
down_revision = '92980ac156ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rfid', 'uid',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rfid', 'uid',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
