"""empty message

Revision ID: ef3e2c33d2e4
Revises: 6d3158fd1d5b
Create Date: 2021-03-31 16:14:33.658427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef3e2c33d2e4'
down_revision = '6d3158fd1d5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('gameConfig', 'gameTypeID',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('gameConfig', 'mapID',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('gameConfig', 'mapID',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('gameConfig', 'gameTypeID',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
